# Generated by Django 4.2.11 on 2024-05-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_authors_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
