# Generated by Django 4.2.11 on 2024-05-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_books_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
