# Generated by Django 4.2.11 on 2024-05-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
