# Generated by Django 4.2.11 on 2024-05-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_shippingaddress2_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress2',
            name='id',
            field=models.IntegerField(default=1),
        ),
    ]
